services:
  basegoimage:
    build:
      dockerfile: Dockerfile.base
    image: basegoimage

#    pgadmin:
#      image: dpage/pgadmin4
#      ports:
#        - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
#      environment:
#        PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
#        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      volumes:
#        - ./.data/pgadmin:/var/lib/pgadmin

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data
    ports:
      - 54321:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/server.key:/root/ssl/server.key
      - ./configs/server.crt:/root/ssl/server.crt
    ports:
      - 7443:443
      - 7080:80
    depends_on:
      - onehub
      - ohfe

#  nextfe:
#    build: ./nextfe
#    volumes:
#       - ./nextfe:/app
#       - /app/node_modules
#       - /app/.next
#    restart: always
#    ports:
#      - 4000:4000
#    stdin_open: true

  ohfe:
    depends_on:
      - basegoimage
    build:
      context: ./ohfe
    volumes:
      - ./ohfe:/app
    command: ["air", "-c", "ohfe/.air.toml"]
    environment:
      ONEHUB_API_ENDPOINT: http://onehub:9080/api
      ONEHUB_GRPC_ENDPOINT: onehub:9090
    ports:
      - 5080:5000
      - 9092:9091

  onehub:
    depends_on:
      - basegoimage
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    volumes:
      # - ./.air.toml:/app/.air.toml:ro
      # - ./go.mod:/app/go.mod:ro
      # - ./go.sum:/app/go.sum:ro
      - ./cmd:/app/cmd
      - ./gen:/app/gen
      - ./datastore:/app/datastore
      - ./protos:/app/protos
      - ./services:/app/services
    command: ["air", "-c", "cmd/backend/.air.toml"]
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ONEHUB_DB_ENDPOINT: ${ONEHUB_DB_ENDOINT}
    ports:
      - 9080:9080
      - 9000:9000
      - 9091:9091

