version: '3.9'
services:
  basegoimage:
    build:
      dockerfile: Dockerfile.base
    image: basegoimage

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    environment:
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data
    ports:
      - 54321:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/server.key:/root/ssl/server.key
      - ./configs/server.crt:/root/ssl/server.crt
    ports:
      - 7443:443
      - 7080:80
    depends_on:
      - onehub
      - nextfe 
        # - ohfe

  typesense:
    image: typesense/typesense:0.25.0
    restart: on-failure
    ports:
      - 8108:8108
    volumes:
      - ./.data/typesensedata:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  onehub:
    depends_on:
      - basegoimage
      - postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      # - ./.air.toml:/app/.air.toml:ro
      # - ./go.mod:/app/go.mod:ro
      # - ./go.sum:/app/go.sum:ro
      - ./cmd:/app/cmd
      - ./gen:/app/gen
      - ./datastore:/app/datastore
      - ./services:/app/services
      - ./protos:/app/protos
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ONEHUB_DB_ENDPOINT: ${ONEHUB_DB_ENDOINT}
    ports:
      - 8080:8080
      - 9000:9000
      - 9091:9091

  nextfe:
    build: ./nextfe
    volumes:
       - ./nextfe:/app
       - /app/node_modules
       - /app/.next
    restart: always
    ports:
      - 4000:4000
    stdin_open: true

#  ohfe:
#    depends_on:
#      - basegoimage
#    build:
#      context: ./ohfe
#    volumes:
#      # - ./ohfe/.air.toml:/app/.air.toml:ro
#      # - ./ohfe/go.mod:/app/go.mod:ro
#      # - ./ohfe/go.sum:/app/go.sum:ro
#      - ./ohfe/cmd:/app/cmd
#    environment:
#      ONEHUB_ENDPOINT: http://onehub:8080/api
#      ONEHUB_GRPC_ENDPOINT: onehub:9090
#    ports:
#      - 5080:5000
#      - 9092:9091
