networks:
  onehubnetwork:
    external: true

services:
  nginx:
    networks:
      - onehubnetwork
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/server.key:/root/ssl/server.key
      - ./configs/server.crt:/root/ssl/server.crt
    ports:
      - 7443:443
      - 7080:80
    depends_on:
      - onehub
      - ohfe
      - nextfe

  nextfe:
    networks:
      - onehubnetwork
    build: ./nextfe
    volumes:
       - ./nextfe:/app
       - /app/node_modules
       - /app/.next
    restart: always
      # ports:
      # - 4000:4000
    stdin_open: true

  ohfe:
    networks:
      - onehubnetwork
    build:
      context: ./ohfe
      dockerfile: Dockerfile.debug
    restart: unless-stopped
    volumes:
      - ./ohfe:/app
    environment:
      ONEHUB_API_ENDPOINT: http://onehub:9080/api
      ONEHUB_GRPC_ENDPOINT: onehub:9090
    ports:
      # - 5080:5000
      - 9091:9091

  onehub:
    networks:
      - onehubnetwork
    build:
      context: .
      dockerfile: ./cmd/backend/Dockerfile.debug
    volumes:
      # - ./.air.toml:/app/.air.toml:ro
      # - ./go.mod:/app/go.mod:ro
      # - ./go.sum:/app/go.sum:ro
      - ./cmd/backend:/app/cmd/backend
      - ./clients:/app/clients
      - ./datastore:/app/datastore
      - ./protos:/app/protos
      - ./services:/app/services
      - ./gen:/app/gen
        # command: ["air", "-c", "cmd/backend/.air.toml"]
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ONEHUB_DB_ENDPOINT: ${ONEHUB_DB_ENDOINT}
    ports:
      - 9080:9080
      - 9000:9000
      - 9092:9091

  dbsync:
    networks:
      - onehubnetwork
    build:
      context: ./
      dockerfile: ./cmd/dbsync/Dockerfile.debug
    volumes:
      # - ./ohfe/.air.toml:/app/.air.toml:ro
      # - ./ohfe/go.mod:/app/go.mod:ro
      # - ./ohfe/go.sum:/app/go.sum:ro
      - ./cmd/dbsync:/app/cmd/dbsync
      - ../dbsync:/app/locallinks/dbsync
      - ./clients:/app/clients
    ports:
      - 3333:3333
      - 9093:9091
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ONEHUB_DB_ENDPOINT: ${ONEHUB_DB_ENDOINT}
      DBSYNC_CTRL_NAMESPACE: ${DBSYNC_CTRL_NAMESPACE}
      DBSYNC_WM_TABLENAME: ${DBSYNC_WM_TABLENAME}
      DBSYNC_PUBNAME: ${DBSYNC_PUBNAME}
      DBSYNC_REPLSLOT: ${DBSYNC_REPLSLOT}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_HOST: ${TYPESENSE_HOST}
