import React, { useState, useEffect, useContext } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TopicListPanel from '@/components/TopicListPanel'
import TopicPanel from '@/components/TopicPanel'
import { Api } from '@/core/Api'
const api = new Api()

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [currTopicId, setCurrTopicId] = React.useState(null)
  const onTopicSelected = (topic: any) => {
    console.log("Selected: ", topic)
    setCurrTopicId(topic.id)
  }

  const signInButtonLabel = "Sign In"
  const onSigninButtonClicked = () => {
  }

  return (
  <>
    <Head>
    <title>OneHub Client Demo</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.header}>
        <h2>OneHub Playground</h2>
        <div className={styles.headerRightToolbar}>
            <button onClick={onSigninButtonClicked}>{signInButtonLabel}</button>
        </div>
      </div>
      <div className={styles.left}>
        <TopicListPanel onTopicSelected={onTopicSelected}/>
      </div>
      <div className={styles.centerpanel}>
        <TopicPanel topicId = {currTopicId} />
      </div>
      <div className={styles.footer}>
      </div>
    </main>
  </>
  )
}
