
export const ADJECTIVES = [
  "adaptable",
  "adventurous",
  "affable",
  "affectionate",
  "agreeable",
  "ambitious",
  "amiable",
  "amicable",
  "amusing",
  "brave",
  "bright",
  "broad-minded",
  "calm",
  "careful",
  "charming",
  "communicative",
  "compassionate	",
  "conscientious",
  "considerate",
  "convivial",
  "courageous",
  "courteous",
  "creative",
  "decisive",
  "determined",
  "diligent",
  "diplomatic",
  "discreet",
  "dynamic",
  "easygoing",
  "emotional",
  "energetic",
  "enthusiastic",
  "exuberant",
  "fair-minded",
  "faithful",
  "fearless",
  "forceful",
  "frank",
  "friendly",
  "funny",
  "generous",
  "gentle",
  "good",
  "gregarious",
  "hard-working",
  "helpful",
  "honest",
  "humorous",
  "imaginative",
  "impartial",
  "independent",
  "intellectual",
  "intelligent",
  "intuitive",
  "inventive",
  "kind",
  "loving",
  "loyal",
  "modest",
  "neat",
  "nice",
  "optimistic",
  "passionate",
  "patient",
  "persistent	",
  "pioneering",
  "philosophical",
  "placid",
  "plucky",
  "polite",
  "powerful",
  "practical",
  "pro-active",
  "quick-witted",
  "quiet",
  "rational",
  "reliable",
  "reserved",
  "resourceful",
  "romantic",
  "self-confident",
  "self-disciplined",
  "sensible",
  "sensitive",
  "shy",
  "sincere",
  "sociable",
  "straightforward",
  "sympathetic",
  "thoughtful",
  "tidy",
  "tough",
  "unassuming",
  "understanding",
  "versatile",
  "warmhearted",
  "willing",
  "witty",
]

export const ANIMALS = [
  'Tiger',
  'Lion',
  'Elephant',
  'Leopard',
  'Panther',
  'Cheetah',
  'Wolf',
  'Jaguar',
  'Hyena',
  'Giraffe',
  'Deer',
  'Zebra',
  'Gorilla',
  'Monkey',
  'Chimpanzee',
  'Bear',
  'Wild Boar',
  'Hippopotamus',
  'Kangaroo',
  'Rhinoceros',
  'Crocodile',
  'Panda',
  'Squirrel',
  'Mongoose',
  'Porcupine',
  'Koala Bear',
  'Wombat',
  'Meerkat',
  'Otter',
  'Hedgehog',
  'Possum',
  'Chipmunk',
  'Squirrel',
  'Raccoon',
  'Jackal',
  'Hare',
  'Mole',
  'Rabbit',
  'Alligator',
  'Monitor Lizard',
  'Oryx',
  'Elk',
  'Badger',
  'Dinosaur',
  'Pangolin',
  'Mole',
  'Okapi',
  'Camel',
  'Wild cat',
  'Coyote',
  'Bison',
  'African Elephant',
  'Aardvark',
  'Antelope',
  'Alpine Goat',
  'Komodo Dragon',
  'Bearded Dragon',
  'Royal Bengal Tiger',
  'Flying Squirrel',
  'Emu',
  'Eagle',
  'Eel',
  'Asiatic Lion',
  'Armadillo',
  'Beaver',
  'Emperor Penguin',
  'Baboon',
  'Bat',
  'Chameleon',
  'Bull',
  'Giant Panda',
  'Chihuahua',
  'Orangutan',
  'Chinchillas',
  'Hawk',
  'Iguana',
  'Ibis',
  'Ibex',
  'King Cobra',
  'Jellyfish',
  'Goose',
  'Walrus',
  'Seal',
  'Skink',
  'Markhor',
  'Falcon',
  'Bull Shark',
  'Arctic Wolf',
  'Owl',
  'Bulbul',
  'Bobcat',
  'Guinea Pig',
  'Yak',
  'Reindeer',
  'Moose',
  'Puma',
  'Okapi',
  'Marten',
  'Squirrel Monkey',
  'Caracal'
]

export const RandomName = () => {
  let adj = ADJECTIVES[Math.floor((Math.random()*ADJECTIVES.length))]
  adj = adj[0].toUpperCase() + adj.substring(1)
  let animal = ANIMALS[Math.floor((Math.random()*ANIMALS.length))]
  animal = animal[0].toUpperCase() + animal.substring(1)
  return adj + " " + animal
}
