FROM --platform=linux/amd64 dagmeister/golangdev:latest

WORKDIR /app

COPY locallinks ./locallinks
COPY Makefile go.mod go.sum ./
RUN mkdir cmd clients
COPY cmd ./cmd
COPY clients ./clients
RUN ls -al

RUN go mod download

WORKDIR /app/cmd/dbsync

# Uncomment below line to eee if the build works as a test
# Usually this will be useful if you have added or removed folders
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/main main.go

CMD ["air"]
